### ISSUE TITLE
How to pass environment variables to docker-compose?

### ISSUE THREAD

**Issue by tkambler** [leighmcculloch/vagrant-docker-compose#33]
Can you provide an example in which environment variables, which are defined within the `Vagrantfile`, are made available to the `docker-compose` command? The goal is to have a `Dockerfile` that references them, like so:

```
RUN ["login-npm", "${NPM_USERNAME}", "${NPM_PASSWORD}", "${NPM_EMAIL}"]
```

Nothing I've tried so far seems to work.

Thank you.

**Comment by leighmcculloch** [comment]
@tkambler There isn't a way to do this in the current version (1.0.0), but I think this could be added without a great deal of effort. Stay tuned.

**Comment by tkambler** [comment]
@leighmcculloch Here's the situation:

I've got a collection images that need to be built, but the build process includes some dependency grabs that require credentials. I obviously don't want to add that information to the Dockerfile, so I'd like to be able to pass it in as config via the Vagrantfile.

I hear you re: environment variables. I may be on another wild goose chase, but I do think I may be on the verge of making this work with ARG options. I'll post any progress shortly.

**Comment by tkambler** [comment]
Closing this out for now. While not ideal, due to the duplication (for each service), I managed to get to a semi-decent state by doing the following:

The docker-compose.yml file looks like this:

```
version: '2'
services:
  service:
    build:
      context: ./resources/service
      dockerfile: docker/Dockerfile
      args:
        - NPM_USERNAME=username
        - NPM_PASSWORD=password
        - NPM_EMAIL=user@domain
        - NPM_REGISTRY=https://npm.domain.com
    container_name: service
    entrypoint: npm start
    working_dir: /opt/service
    environment:
    - NODE_PATH=./lib
    - NODE_ENV=development
    ports:
    - "7020:7020"
```

That service's Dockerfile looks like this:

```
FROM node
# ...
ARG NPM_REGISTRY
ARG NPM_USERNAME
ARG NPM_PASSWORD
ARG NPM_EMAIL
RUN ["npm", "set", "always-auth", "true"]
RUN npm set registry "${NPM_REGISTRY}"
RUN login-npm "${NPM_USERNAME}" "${NPM_PASSWORD}" "${NPM_EMAIL}"
```
