### ISSUE TITLE
One of "build_dir" or "image" must be set

### ISSUE THREAD

**Issue by HeathNaylor** [leighmcculloch/vagrant-docker-compose#39]
After running `vagrant up` I get the following error:

```
There are errors in the configuration of this machine. Please fix
the following errors and try again:

docker provider:
* One of "build_dir" or "image" must be set
```

Vagrantfile:
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.provision :docker
  config.vm.provision :docker_compose, rebuild: true, run: "always", yml: "/vagrant/docker-compose.yml"
end
```

docker-compose.yml
```
services: 
  redis: 
    image: redis
  web: 
    build: "."
    depends_on: 
      - redis
    ports: 
      - "5000:5000"
    volumes: 
      - ".:/code"
version: "2"
```
