### ISSUE TITLE
Names of created images

### ISSUE THREAD

**Issue by psychemedia** [leighmcculloch/vagrant-docker-compose#7]
I'm using vagrant-docker-compose to create a set of images within a VM using one `Vagrantfile` & `docker-compose.yml` file, bundling that VM and then launching containers within it using another `Vagrantfile` & `docker-compose.yml` file.

The original images (which are built) are automatically named as eg `vagrant_foo` and `vagrant_bar` based on the name given in the YAML file. These images exist in the VM, eg as per:

```
$docker images

REPOSITORY                   TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
vagrant_ipynb                latest              1bb94ebe6e38        3 hours ago         3.138 GB
vagrant_mongo                latest              51be69974278        3 hours ago         278 MB
ipython/scipystack           latest              720dc652b731        24 hours ago        2.857 GB
```

If I set eg `image: vagrant_mongo` as the name of an image in a new `docker-compose.yml` file, I get the error `Error: image library/vagrant_mongo:latest not found`.

If I set the name as `./vagrant_mongo ` I get `HTTPS endpoint unresponsive and insecure mode isn't enabled.`.

So how do I address the created images? Is there anyway I can configure `vagrant-docker-compose` to get names of the form `myimage/vagrant_mongo` and then try to load those

**Comment by psychemedia** [comment]
When rerunning a `vagrant` script, I keeping getting an error on one of my containers (quite a large one) getting ripped down and replaced:

```
Recreating vagrant_devpostgresdata_1...
Recreating vagrant_devpostgres_1...
Recreating f9ceb317c4_f9ceb317c4_f9ceb317c4_vagrant_ipynb_1...
```

Each time I reload the machine, I get another level of nesting on the `ipynb` container which then causes a `Duplicate bind mount /notebooks` error, presumably as multiple differently named containers try to mount the /notebooks` directory?

Here's the relevant `Dockerfile':

```
devpostgresdata:
    command: echo created
    image: busybox
    volumes: 
        - /var/lib/postgresql/data
 
devpostgres:
    environment:
        - POSTGRES_PASSWORD=PGPass
    image: postgres
    ports:
        - "5432:5432"
    volumes_from:
        - devpostgresdata
 
ipynb:
  image: psychemedia/tm351_scipystacknserver:tm351d3test
  ports:
    - "8888:8888"
  volumes:
    - ./notebooks/:/notebooks/
  links:
    - devpostgres:postgres
    - mongo:mongo
    - openrefine:openrefine
  privileged: true
```

and the Vagrantfile:

```
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provider :virtualbox do |virtualbox|
  	virtualbox.memory = 1024
  end
  
  config.vm.network(:forwarded_port, guest: 8888, host: 8351,auto_correct: true)
  
  #Check that necessary host directories are in place
  config.vm.provision :shell, :inline => <<-SH
    mkdir -p notebooks
  SH

  #If you need to get into a container:
  # vagrant ssh
  # docker exec -it CONTAINERNAME bash
  
  config.vm.provision :docker_compose, yml: "/vagrant/docker-compose.yml", run: "always"
end
```
